debug: false
logging:
  config: classpath:logback.xml
server:
  port: 8080
  servlet:
    context-path: /api
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/app?characterEncoding=UTF-8&useUnicode=true&serverTimezone=UTC
    username: root
    password: 324ppwWin
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  jackson:
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: true
  redis:
    # 地址
    host: localhost
    # 端口，默认为6379
    port: 6379
    # 密码
    password:
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
wechat:
  mini-program:
    customer:
      app-id: wxe53979885c7f744e
      app-secret: c12ee1495aaa93c39679fec5e5350511
      template-id: <templateId>
      page-url: <pageUrl>
      sign-url: <pageUrl>

# MyBatis配置
mybatis:
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mybatis/**/*Mapper.xml
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: is_deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations: classpath*:/mapper/**/*Mapper.xml
  type-aliases-package: com.weekly.**.pojo.po
  configuration:
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler
